server:
  port: 80


spring:
  application:
    name: cloud-order-service
eureka:
  client:
    #是否从注册中心中获取已有的注册信息
    fetch-registry: true
    #是否自动注册进入到eureka中
    register-with-eureka: true
    service-url:
      #集群模式的添加链接地址
      defaultZone: http://localhost:7001/eureka,http://eureka7003.com:7003/eureka/
      #单机模式添加链接地址
      #defaultZone:http://localhost:7001/eureka
  instance:
    instance-id: consumer80 #修改在服务注册中心中显示的名字
    prefer-ip-address: true #修改移动到访问路径中显示ip地址