server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb:http://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/find/** # 断言，路径相匹配的进行路由
            - After=2022-05-07T15:10:41.575+08:00[Asia/Shanghai] #表示用户访问时的时间要在这之后
            #- Before=2022-05-07T16:10:41.575+08:00[Asia/Shanghai] #表示用户访问时的时间要在这之前
            #表示用户使用时间要在这两个数据之间
            #- Between=2022-05-07T15:10:41.575+08:00[Asia/Shanghai],2022-05-07T16:10:41.575+08:00[Asia/Shanghai]
         #   - Cookie=username,zecan
         #   - Header=X-Request-Id, \d+
        - id: payment_route2
          uri: lb:http://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/time #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
