server:
  port: 80


eureka:
  client:
    register-with-eureka: false #不将直接注册到服务中心中
    service-url:
      defaultZone: http://localhost:7001/eureka,http://eureka7003.com:7003/eureka/
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接使用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

  #开启日志的feign客户端
logging:
  level:
     #feign日志以什么级别监控哪个接口
    com.zecan.springcloud.service.OpenFeignServer: debug    #写你们自己的包名
